BOT_NAME = "carbon38"
SPIDER_MODULES = ["carbon38.spiders"]
NEWSPIDER_MODULE ="carbon38.spiders"
ROBOTSTXT_OBEY=False
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
LOG_LEVEL='DEBUG'
FEED_EXPORT_ENCODING="utf-8"
TWISTED_REACTOR='twisted.internet.selectreactor.SelectReactor'